
public class Main {
    public static void main(String[] args) {

        // defining variables
        int numGenerated, modulus;

        // generate random number and cast it to an int variable
        numGenerated = (int ) (Math.random() * 100);
        System.out.println("The number generated is : " + numGenerated);

        // divide the number generated by the 2 using modulus
        modulus = numGenerated % 2;

        if (modulus == 1){
            System.out.println("\nThe number generated is an odd number [ not even ]");
        }
        else{
            System.out.println("\nThe number generated is an even number [ even ]");
        }
    }
}